apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-example
  namespace: dev
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: node-example
    spec:
      containers:
        - name: node-example
          image: sunnyouch/node-example:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi